### ISSUE TITLE
can't find method 0

### ISSUE THREAD

**Issue by zemlanin** [EugeneN/DNA.js#14]
Если у виджета нет функций (реализация не возвращает объект), то повторный вызов экстенда невозможен

``` coffeescript
protocol = [
    ['*cons*', [], {concerns: {before: [extract_opts]}}]
]


impl = (node, node_data) ->
    jnode = $ node

    if node_data.Utm
        jnode.mousedown ->
            start_sym = if '?' not in jnode.attr('href') then '?' else '&'
            utm_href = jnode.attr('href') + start_sym + node_data.Utm
            jnode.attr('href', utm_href)
            true
    {} # решение
```

**Comment by bvsn** [comment]
Ну так, а чего ты ожидал? :)
Ты описал конструкцию с которой DNA не работает, если у тебя есть реализация твоего виджета без никаких методов, то написание в конце "{}" - вполне правильное решение.

**Comment by zemlanin** [comment]
Нормальный ERROR, а не что-то про нулевой метод

**Comment by EugeneN** [comment]
Fixed long time ago
