### ISSUE TITLE
Improve data-extend

### ISSUE THREAD

**Issue by bvsn** [EugeneN/DNA.js#20]
The protocols that are defined in the `data-extend`, should replace implementation of the same methods of the protocols that are defined by default.

Example:
default protocol IDom has a method `html`, custom protocol Appearance also has a method `html`:
data-extend="Appearance"
data-subscribe='click : "some html" | html'

Now it cause an error. I think that we are should use special symbol `/` only when conflict of the methods are presented in the defined protocols in the `data-extend`.

**Comment by brabadu** [comment]
Last DNA version enforces you to explicitly define namespaces. So every
call to a method that does not have namespace shows warning message. It may
be changed to fall with error later

óÕÂÏÔÁ, 21 ×ÅÒÅÓÎÑ 2013 Ò. ËÏÒÉÓÔÕ×ÁÞ Andrew Bovsunovskiy ÎÁÐÉÓÁ×:

> The protocols that are defined in the data-extend, should replace
> implementation of the same methods of the protocols that are defined by
> default.
> 
> Example:
> default protocol IDom has a method html, custom protocol Appearance also
> has a method html:
> data-extend="Appearance"
> data-subscribe='click : "some html" | html'
> 
> Now it cause an error. I think that we are should use special symbol /only when conflict of the methods are presented in the defined protocols in
> the data-extend.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/EugeneN/DNA.js/issues/20
> .

## 

Boryslav Larin
+38 063 272 21 44 | brabadu@gmail.com
http://brabadu.com
Twitter: http://twitter.com/brabadu

**Comment by EugeneN** [comment]
fixed a month ago
