### ISSUE TITLE
Subscribe sequence stops, when passing empty list as argument to some interface method

### ISSUE THREAD

**Issue by AlexMost** [EugeneN/DNA.js#22]
Example:
subscribe="click: someMethod@Interface []"

click will not fire because bool([]) - returns false.
This issue will occur if we will try to pass 0, [], or false as argument to some method.

**Comment by brabadu** [comment]
FAIL

**Comment by pavlo-v-chernykh** [comment]
:+1:

**Comment by AlexMost** [comment]
fixed here https://github.com/EugeneN/DNA.js/commit/8ac56348700692af5bf1619696a2506e741f5e44.
thx
